/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hexademical
 */
public class Management extends javax.swing.JFrame {

    /**
     * Creates new form Management
     */
    public Management() {
        initComponents();

        MDatabase.setText("Database");
        MUserManagement.setText("User Management");

        MDatabase.getItem(0).setText("Show All Databases");
        MDatabase.getItem(1).setText("Show All Collections");
        MDatabase.getItem(2).setText("Exit");
        
        PanelShowDatabases.setVisible(false);
        PanelShowCollections.setVisible(false);                

            
        // Show All Databases listener
        MDatabase.getItem(0).addActionListener((e) -> {
            // TODO: Implement later.
            System.out.println("Show All Databases listener executed.");
            PanelShowCollections.setVisible(false);// hide collections panel
            PanelShowDatabases.setVisible(true); // show databases panel
        });

        // Show All Collections listener
        MDatabase.getItem(1).addActionListener((e) -> {
            // TODO: Implement later.
            System.out.println("Show All Collections listener executed.");
            PanelShowDatabases.setVisible(false); // hide databases panel
            PanelShowCollections.setVisible(true); // show collections panel
        });

        // Exit listener
        MDatabase.getItem(2).addActionListener((e) -> {
            // TODO: Implement later.
            System.out.println("Exit listener executed.");
            System.exit(0); // exit program.
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelShowDatabases = new javax.swing.JPanel();
        LTitle = new javax.swing.JLabel();
        BTNViewDatabases = new javax.swing.JButton();
        SPDatabases = new javax.swing.JScrollPane();
        LTDatabases = new javax.swing.JList<>();
        PanelShowCollections = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        MDatabase = new javax.swing.JMenu();
        MIShowDatabases = new javax.swing.JMenuItem();
        MIShowCollections = new javax.swing.JMenuItem();
        MIExit = new javax.swing.JMenuItem();
        MUserManagement = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Management System Development for BigC Company");

        LTitle.setText("Database View");

        BTNViewDatabases.setText("View Databases");
        BTNViewDatabases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNViewDatabasesActionPerformed(evt);
            }
        });

        SPDatabases.setViewportView(LTDatabases);

        javax.swing.GroupLayout PanelShowDatabasesLayout = new javax.swing.GroupLayout(PanelShowDatabases);
        PanelShowDatabases.setLayout(PanelShowDatabasesLayout);
        PanelShowDatabasesLayout.setHorizontalGroup(
            PanelShowDatabasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelShowDatabasesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelShowDatabasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LTitle)
                    .addGroup(PanelShowDatabasesLayout.createSequentialGroup()
                        .addComponent(BTNViewDatabases)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SPDatabases, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        PanelShowDatabasesLayout.setVerticalGroup(
            PanelShowDatabasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelShowDatabasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelShowDatabasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNViewDatabases)
                    .addComponent(SPDatabases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelShowCollectionsLayout = new javax.swing.GroupLayout(PanelShowCollections);
        PanelShowCollections.setLayout(PanelShowCollectionsLayout);
        PanelShowCollectionsLayout.setHorizontalGroup(
            PanelShowCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        PanelShowCollectionsLayout.setVerticalGroup(
            PanelShowCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        MDatabase.setText("Database");

        MIShowDatabases.setText("SHOW_DATABASES");
        MDatabase.add(MIShowDatabases);

        MIShowCollections.setText("SHOW_COLLECTIONS");
        MIShowCollections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIShowCollectionsActionPerformed(evt);
            }
        });
        MDatabase.add(MIShowCollections);

        MIExit.setText("EXIT");
        MDatabase.add(MIExit);

        MenuBar.add(MDatabase);

        MUserManagement.setText("User Management");
        MenuBar.add(MUserManagement);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelShowCollections, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelShowDatabases, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelShowCollections, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelShowDatabases, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIShowCollectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIShowCollectionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIShowCollectionsActionPerformed

    private void BTNViewDatabasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNViewDatabasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNViewDatabasesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNViewDatabases;
    private javax.swing.JList<String> LTDatabases;
    private javax.swing.JLabel LTitle;
    private javax.swing.JMenu MDatabase;
    private javax.swing.JMenuItem MIExit;
    private javax.swing.JMenuItem MIShowCollections;
    private javax.swing.JMenuItem MIShowDatabases;
    private javax.swing.JMenu MUserManagement;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel PanelShowCollections;
    private javax.swing.JPanel PanelShowDatabases;
    private javax.swing.JScrollPane SPDatabases;
    // End of variables declaration//GEN-END:variables
}
