

import com.mongodb.MongoClient;
import com.mongodb.MongoClientOptions;
import com.mongodb.ServerAddress;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hexademical
 */
public class ShowDB extends javax.swing.JFrame {
    
    // modelListDocument : DefaultListModel 
    // using for set to show list components so it's private
    private final DefaultListModel modelListDocument = new DefaultListModel();
            
    /**
     * Creates new form ShowDB
     */
    public ShowDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBTitleText = new javax.swing.JLabel();
        BTNViewDatabase = new javax.swing.JButton();
        SPDocumentList = new javax.swing.JScrollPane();
        LDocumentList = new javax.swing.JList<>();
        BTNExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Show DB Name");

        LBTitleText.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        LBTitleText.setText("Database View & Management");

        BTNViewDatabase.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BTNViewDatabase.setText("Show Documents");
        BTNViewDatabase.setMargin(new java.awt.Insets(3, 14, 3, 14));
        BTNViewDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNViewDatabaseActionPerformed(evt);
            }
        });

        SPDocumentList.setViewportView(LDocumentList);

        BTNExit.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BTNExit.setText("EXIT");
        BTNExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBTitleText)
                        .addGap(0, 128, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNViewDatabase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SPDocumentList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTNExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBTitleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNViewDatabase)
                    .addComponent(SPDocumentList, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(BTNExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Using for alert everything.
    public void AlertBox(String title, String description, int messageType)
    {
        JOptionPane.showMessageDialog(null, description, title, messageType); 
    }
    
    //  Using for exit button
    private void BTNExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNExitActionPerformed
        System.exit(0); // exit program with exit code 0.
    }//GEN-LAST:event_BTNExitActionPerformed

    private void BTNViewDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNViewDatabaseActionPerformed
        try
        {
            // options when connect to database
            MongoClientOptions connOptions = MongoClientOptions.builder()
                .connectTimeout(5000) // connection timeout set to 5 ms
                .serverSelectionTimeout(5000) // selection timeout set to 5 ms
                .build();
            
            // address of connection with port
            // we using local database
            ServerAddress connectAddress = new ServerAddress("localhost", 27017);
            
            // connect to database
            MongoClient client = new MongoClient(connectAddress, connOptions);
            
            
            modelListDocument.clear(); // clear model list before add docs name.
            for(String docName : client.getDatabaseNames())
            {
                modelListDocument.addElement(docName); // loop and add each doc name.
            }
                        
            // set model to LDocumentList
            // then it's will re-render show list.
            LDocumentList.setModel(modelListDocument); 
        }
        catch(Exception e)
        {
            // alert box error
            AlertBox("Something's went wrong!", e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTNViewDatabaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNExit;
    private javax.swing.JButton BTNViewDatabase;
    private javax.swing.JLabel LBTitleText;
    private javax.swing.JList<String> LDocumentList;
    private javax.swing.JScrollPane SPDocumentList;
    // End of variables declaration//GEN-END:variables
}
